# Generated by Django 5.1.4 on 2025-01-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completada:'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Título:'),
        ),
    ]
